### ISSUE TITLE
meine Fehlermeldung oilFox version 0.0.1

### ISSUE THREAD

**Issue by Meraluna** [iobroker-community-adapters/ioBroker.oilfox#1]
host.raspberrypi | 2018-12-29 22:18:38.748 | info | Restart adapter system.adapter.oilfox.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2018-12-29 22:18:38.748 | error | instance system.adapter.oilfox.0 terminated with code 1 ()
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at Function.Module._load (module.js:497:3)
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at tryModuleLoad (module.js:505:12)
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at Module.load (module.js:565:32)
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at Object.Module._extensions..js (module.js:663:10)
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at Module._compile (module.js:652:30)
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:7:15)
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at require (internal/module.js:11:18)
host.raspberrypi | 2018-12-29 22:18:38.748 | error | Caught by controller[0]:     at Module.require (module.js:596:17)
host.raspberrypi | 2018-12-29 22:18:38.747 | error | Caught by controller[0]:     at Function.Module._load (module.js:474:25)
host.raspberrypi | 2018-12-29 22:18:38.747 | error | Caught by controller[0]:     at Function.Module._resolveFilename (module.js:547:15)
host.raspberrypi | 2018-12-29 22:18:38.747 | error | Caught by controller[0]: Error: Cannot find module '@iobroker/adapter-core'
host.raspberrypi | 2018-12-29 22:18:38.747 | error | Caught by controller[0]:     ^
host.raspberrypi | 2018-12-29 22:18:38.747 | error | Caught by controller[0]:     throw err;
host.raspberrypi | 2018-12-29 22:18:38.747 | error | Caught by controller[0]: module.js:549
host.raspberrypi | 2018-12-29 22:18:38.379 | info | instance system.adapter.oilfox.0 started with pid 17785

**Comment by Meraluna** [comment]
Einloggen geht beide kontrollichter grün nur ist nirgens ein status oder ein wert neu erschienen in den Objekten.

**Comment by Meraluna** [comment]
Einlogen geht jedoch keine Neuen Objekte geschrieben bei Ereignissen sind Logs von OilFox


stateChange | system.adapter.oilfox.0.outputCount | 8 | true | oilfox.0 | 2018-12-30 14:13:33.229 | 2018-12-30 14:13:07.075
-- | -- | -- | -- | -- | -- | --
stateChange | system.adapter.oilfox.0.inputCount | 0 | true | oilfox.0 | 2018-12-30 14:13:33.229 | 2018-12-30 14:13:07.074
stateChange | system.adapter.oilfox.0.uptime | 2 | true | oilfox.0 | 2018-12-30 14:13:33.228 | 2018-12-30 14:13:33.228
stateChange | system.adapter.oilfox.0.memHeapUsed | 7.32 | true | oilfox.0 | 2018-12-30 14:13:33.227 | 2018-12-30 14:13:33.227
stateChange | system.adapter.oilfox.0.memHeapTotal | 15.03 | true | oilfox.0 | 2018-12-30 14:13:33.226 | 2018-12-30 14:13:33.226
stateChange | system.adapter.oilfox.0.memRss | 31.72 | true | oilfox.0 | 2018-12-30 14:13:33.225 | 2018-12-30 14:13:33.225
stateChange | system.adapter.oilfox.0.connected | true | true | oilfox.0 | 2018-12-30 14:13:33.224 | 2018-12-30 14:13:33.224
stateChange | system.adapter.oilfox.0.alive | true | true | oilfox.0 | 2018-12-30 14:13:33.220 | 2018-12-30 14:13:33.220

**Comment by peoples0815** [comment]
Funktioniert bei mir nun auch!
Nur welcher ist der Wert für den aktuellen Stand?

**Comment by jogibear9988** [comment]
devices.0.metering.liters
