### ISSUE TITLE
oilfox 2

### ISSUE THREAD

**Issue by Ridesa** [iobroker-community-adapters/ioBroker.oilfox#11]
Läuft der adapter auch mit dem oilfox 2 ?

**Comment by jogibear9988** [comment]
kp. was ist an dem anders? 
ich kommuniziere ja nicht direkt mit dem oilfox sondern mit der cloud von denen, denke der sollte dann schon gehen, zumindest mit wenig aufwand.

**Comment by Ridesa** [comment]
Funktioniert super Adapter danke 👍

**Comment by jogibear9988** [comment]
was ist der unterschied zum 1er?
