### ISSUE TITLE
Process occasionally stuck

### ISSUE THREAD

**Issue by lxffm** [iobroker-community-adapters/ioBroker.oilfox#110]
**Describe the bug**  
Sometimes I observe that no new data is obtained for a couple of days. While investigating it I found out that, in this situation  host.iobroker is logging:

host.iobroker |   | 2023-04-20 20:00:00.031 | warn | instance system.adapter.oilfox.0 already running with pid 28434
-- | -- | -- | -- | --

After killing the process via SSH, the adapter is correctly polling the data according to the schedule.

**To Reproduce**  
1. Let the adapter run
2. wait until issue occurs

**Expected behavior**  
The process must not freeze and the data must be obtained reliably

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: v4.1.2
 - JS-Controller version: 4.0.23
 - Node version: v16.18.1
 - Operating system: Raspberry OS

**Additional context**

**Comment by lxffm** [comment]
Happened to me now again

**Comment by bakerman23** [comment]
Same Problem how staff202.

**Comment by lxffm** [comment]
until someone takes care of this issue, I can give you a workaround. I'm using a script checking frequently whether the process is still running, and kill it if so.

Of course you can spare the pushover and debug blocks if you don't need it

<img width="947" alt="Script" src="https://user-images.githubusercontent.com/3496522/236707095-921f6c8e-95c9-4e4e-a3b4-b6e8659bfeda.png">

**Comment by bakerman23** [comment]
THX. Work with "sudo kill".

**Comment by MiGoller** [comment]
Same problem here since May 2023. Killing the stuck process is the only workaround right now.

**Comment by mcm1957** [comment]
Feedback aus Forum:
https://forum.iobroker.net/topic/66367/oilfox-adapter-keine-funktion-mehr/15

The adapter WORKS with jsc 5 and node 18.
But is gets stuck sometimes

**Comment by mcm1957** [comment]
fixed with 4.2.0

Please open a new issue, if the problem still occures.

**Comment by lxffm** [comment]
Thank you @mcm1957 for you efforts, your care is very much appreciated! unfortunately I need to re-open that issue as it still occurs in v4.2.0 to me.

Best,
Alex

**Comment by mcm1957** [comment]
siehe auch 
https://forum.iobroker.net/topic/68875/oilfox-adapter-aktualisiert-nicht-mehr-hilfe/24

**Comment by mcm1957** [comment]
should be fixed with 4.2.1

Please note or open a new issue if still occuring
