### ISSUE TITLE
direkte Kommunikation mit Oilfox ohne Cloud

### ISSUE THREAD

**Issue by smartboart** [iobroker-community-adapters/ioBroker.oilfox#12]
Hallo,ich finde das mit dem Oilfox ne tolle Sache, da ich aber kein Freund von Cloud Anwendungen bin und lieber alles offline halte bzw. meine smarten Geräte alle fürs internet sperre, wäre ich an einer direkten Kommunikation mit dem oilfox interessiert. Hast du darüber mal nachgedacht? Ist eine direkte Kommunikation denn überhaupt möglich / offene API usw.
Gruß Michael

**Comment by jogibear9988** [comment]
Nicht das ich wüsste!

**Comment by jogibear9988** [comment]
Bin auch kein Fan davon, wird aber immer mehr!
