### ISSUE TITLE
No data or only sporadically

### ISSUE THREAD

**Issue by McR1983** [iobroker-community-adapters/ioBroker.oilfox#177]
Hello,

i get no data or only sporadically.

Only:
error code: GENERIC__INTERNAL_SERVER_ERROR
error status:500

Adapter  v4.3.0

No change to start time
Handy App all ok, right user and pass Credential.

Test:
-Restart Iobroker
- down and upgrade

System:
    Plattform: docker (official image - v9.1.2)
    Betriebssystem: linux
    Architektur: x64
    CPUs: 4
    Geschwindigkeit: 2001 MHz
    Modell: Intel(R) Celeron(R) J4125 CPU @ 2.00GHz
    RAM: 19.3 GB
    Node.js: v18.20.3
    time: 1718040556709
    timeOffset: -120
    NPM: 10.8.0

**Comment by mcm1957** [comment]
Please attach debug log
Please not js-controller version

**Comment by mcreuter** [comment]
At the moment it seems ok... but log here as file
[LOG V4.3.txt](https://github.com/user-attachments/files/15778214/LOG.V4.3.txt)
[LOG V4.2.0.txt](https://github.com/user-attachments/files/15778215/LOG.V4.2.0.txt)

**Comment by mcm1957** [comment]
Well then let's waoit for th eproblem to occure. A log with erro 500 would be fine.

**Comment by mcreuter** [comment]
OK, do it like that :-)

**Comment by mcm1957** [comment]
Lt. log hast du folgendes Schedule eingetragen;:
0/59 * * * *

Damit startet der Adapter zur Minute 59 und zur Minute 0. Das ist zu kurz hintereinander. Trag als schedule eine beliebige Minute ein, also z.B. 27 * * * * wenn du einen stündlichen Update willst. Das sollten den 500 beheben.

**Comment by mcreuter** [comment]
komisch vllt im 4.2 log?
Jetzt ist folgendes eingestellt unter der 4.3
![Screenshot_20240610_224455_Firefox](https://github.com/iobroker-community-adapters/ioBroker.oilfox/assets/120659358/ef0e7b11-acb8-40ff-b9da-31569e750bbe)

**Comment by mcreuter** [comment]
So denke ich....
![Uploading Screenshot_20240610_224859_Firefox.jpg…]()

**Comment by mcm1957** [comment]
Nimm bestimmte Minute 27

**Comment by McR1983** [comment]
Hey im moment ist alles ruhig...

**Comment by mcm1957** [comment]
Danke fürs Feedback
