### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by MeisterHoppel** [iobroker-community-adapters/ioBroker.oilfox#2]
Hi,

i'm getting this Error log:
host.rockpro64 | 2019-01-07 09:01:03.011 | info | instance system.adapter.oilfox.0 terminated with code 0 (OK)
-- | -- | -- | --
oilfox.0 | 2019-01-07 09:01:02.485 | error | ReferenceError: createStateObjects is not defined     at IncomingMessage.summaryRequestResult.on (/opt/iobroker/node_modules/iobroker.oilfox/main.js:76:6)     at emitNone (events.js:111:20)     at Inc
oilfox.0 | 2019-01-07 09:01:02.484 | debug | recieved  data 2:  {"id":"XXXXXX-7465-4ef9-b094-e3db2a8cc6c7","firstName":"Peter","lastName":"Pan","email":"er@xxx-online.de","country":"DE","zipCode":"123456","devices":[{"id":"38eb7493-9a4c-4fcd
oilfox.0 | 2019-01-07 09:01:02.484 | debug | recieved  chunk2: ,"isOrderingEnabled":true,"htmlTermsOrder":"Ich habe die  [Widerrufsbelehrung](https://www.mobene.de/agb/widerrufsrecht.html) zum  Heizölverkauf im Fernabsatz zur Kenntnis genommen und
oilfox.0 | 2019-01-07 09:01:02.482 | debug | recieved  chunk2:  {"id":"7877ab76-7465-4ef9-b094-e3db2a8cc6c7","firstName":"Peter","lastName":"Pan","email":"er@xxxx-online.de","country":"DE","zipCode":"XXXXX","devices":[{"id":"38eb7493-9a4c-4fcd
oilfox.0 | 2019-01-07 09:01:00.784 | info | starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.oilfox, node: v8.15.0
host.rockpro64 | 2019-01-07 09:01:00.049 | info | instance system.adapter.oilfox.0 started with pid 20796
host.rockpro64 | 2019-01-07 09:00:04.044 | info | instance system.adapter.oilfox.0 terminated with code 0 (OK)

All objects are created but empty :-(

Greats
Jens

**Comment by jogibear9988** [comment]
I'll take a look,

I changed the adapter yesterday to be a scheduled one instead of a demon.

But I've not yet tested.

Will fix today

**Comment by jogibear9988** [comment]
Should be fixed.

Please remove Adapter completely (not only the instance). And install it again!
