### ISSUE TITLE
Update von 0.07 auf 1.0.0 nicht möglich

### ISSUE THREAD

**Issue by Snatch2001** [iobroker-community-adapters/ioBroker.oilfox#27]
Das Update von 0.0.7 auf 1.0.0 läuft fehlerfrei durch. Aber der Adapter bleibt auf Version 0.0.7 stehen. Egal wie oft das Update durchgeführt wird.

Bild 1 ist das Update
Bild 2 nach dem Update 

![1](https://user-images.githubusercontent.com/1833577/68577896-409bf680-0471-11ea-9e8f-cb7772a50d48.PNG)
![2](https://user-images.githubusercontent.com/1833577/68577898-409bf680-0471-11ea-8d92-c1ce525b20f8.PNG)

**Comment by jogibear9988** [comment]
should be fixed
