### ISSUE TITLE
Oilfox - Adapter bringt fehler seit heute (12.11.2019)

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.oilfox#28]
Seit heute ca. 16:30 Uhr bekomme ich folgenden Fehler im Log:
`

oilfox.0 | 2019-11-12 21:00:01.039 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
-- | -- | -- | --
oilfox.0 | 2019-11-12 21:00:01.039 | error | at endReadableNT (_stream_readable.js:1143:12)
oilfox.0 | 2019-11-12 21:00:01.039 | error | at IncomingMessage.emit (events.js:203:15)
oilfox.0 | 2019-11-12 21:00:01.039 | error | at IncomingMessage.tokenRequestResult.on (/opt/iobroker/node_modules/iobroker.oilfox/main.js:64:27)
oilfox.0 | 2019-11-12 21:00:01.039 | error | at JSON.parse (<anonymous>)
oilfox.0 | 2019-11-12 21:00:01.039 | error | SyntaxError: Unexpected token < in JSON at position 0
oilfox.0 | 2019-11-12 21:00:01.038 | error | uncaught exception: Unexpected token < in JSON at position 0
oilfox.0 | 2019-11-12 21:00:00.887 | info | starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.oilfox, node: v10.17.0

`

**Comment by jogibear9988** [comment]
sieht so aus als hätte oilfox was umgebaut

**Comment by Snatch2001** [comment]
gleicher Fehler hier.

**Comment by jogibear9988** [comment]
ja, scheint das die api nicht mehr verfügbar ist.
Hab an oilfox geschrieben und keine Antwort bekommen.

**Comment by juettra** [comment]
auch ich habe diesen Fehler. Aber erst seit ich vorhin auf die 1.0.1 upgedated habe. Vorher die 0.5.0 und js-controller 8.6.12 oder so, dann auf node 10.17.0 upgedated und die Oilfox 1.0.1 und dann dieses Problem. Auch wenn ich auf die 0.5.0 zurückgehe bleibt das so,

**Comment by peoples0815** [comment]
Das wäre der Hammer wenn Oilfox die api nicht mehr zur Verfügung stellen würden

**Comment by juettra** [comment]
es gab ja vor 2 Tagen (12.11.19) ein Update der iOS App von Oilfox ...

**Comment by peoples0815** [comment]
Bei Android war das auch so

**Comment by jogibear9988** [comment]
es hat nix mit dem adapter zu tun. die api die ich verwendet hab geht nicht mehr. und ich hab auch keine infos gefunden wie es nun geht

**Comment by juettra** [comment]
ich hoffe, dass sich die Jungs von Oilfox noch bei Dir melden damit der Adapter wieder geht. Habe gerade einen zweiten gekauft (einer für Öltank, einer für Zisterne).

**Comment by jogibear9988** [comment]
vlt. kann sich jemand von euch mal an die wenden? vlt. auch mal anrufen? ich komm da nicht dazu.

**Comment by juettra** [comment]
Hast Du Kontaktdaten?

**Comment by jogibear9988** [comment]
nö. müsst man vlt. auf der homepage suchen.
ich weiss auch nicht mal mehr woher ich die infos für den adapter habe... die warn irgendwo aus nem forum

**Comment by juettra** [comment]
Ich habe die mal über BayWa kontaktiert. Da habe ich meine Foxe her. 

Kann es denn nicht sein, dass es am Update auf den node 10er Version liegt? Bei mir kam das Problem nämlich ziemlich zeitgleich mit dem Update ...

**Comment by jogibear9988** [comment]
Nein.
Die API funzt einfach nicht mehr, habs unter MacOS mit "Postman" probiert.

https://api.oilfox.io/v2/backoffice/session liefert 404

scheint aber es reagiert was auf 
https://api.oilfox.io/v4/backoffice/session . da kommt ein anderer feherl 401

aber was muss man übermitteln... keine ahnung... und mitsniffen ist dank ssl nicht möglich, hab da einiges probiert

**Comment by peoples0815** [comment]
Ich hatte damals Kontakt mit einem Herren von Oilfox als ich versuchte diesen via Script einzubinden bevor du den Adapter gebaut hast. Dem habe ich nochmal geschrieben mal sehen ob sich da was tut

**Comment by Snatch2001** [comment]
Das sind die Kontaktdaten:
LIV-T GmbH

Ganghoferstr. 66e

80339 München

​

Vertreten durch:

Die Geschäftsführer

Dr. Michael Kolb & Til Landwehrmann

 

Kontakt:

E-Mail:    info(@)liv-t.com
Telefon:  089 21540220

**Comment by jogibear9988** [comment]
hat jemand zu denen kontakt aufgenommen?

**Comment by juettra** [comment]
Per Mail gestern abend, aber noch keine Antwort ...

Ralf Juettner

**Comment by peoples0815** [comment]
Ich gehe mal davon aus, dass bisher keiner eine Antwort bekommen hat?

**Comment by juettra** [comment]
Nein, leider nicht. Ich kann da aber gerade auch nicht dran bleiben. Ausserdem fehlt mir, glaube ich, auch etwas der Programmier-Hintergrund...

Ralf Juettner

**Comment by jogibear9988** [comment]
ich kann das schon fixen wenn wir ne antwort bekommen wie...
hab nur keine zeit mich um die klärung zu kümmern...

**Comment by Truwor81** [comment]
Ich habe eine Antwort erhalten. Vielleicht hilft dir das:
Vielen Dank für Ihr Interesse am OilFox und Engagement im Open-Source-Bereich.
Leider können wir bei der Weiterentwicklung keine Rücksicht auf bestehende Tools von Drittanbietern nehmen, weswegen es ab und zu vorkommen kann, dass diese Software dann nicht mehr funktioniert. Wir unterstützen Sie aber gerne bei der Verbesserung Ihrer Software.

Wir haben ein neues Login-Verfahren eingeführt, das auf Basis der OpenID Connect-Spezifikation und JWT funktioniert (mehr Infos dazu hier: https://auth0.com/docs/jwt). Wir hoffen mit diesem Verfahren die Sicherheit des Systems (und damit der Daten unserer Nutzer) verbessern zu können. Deshalb müssen Sie für den Login jetzt einen neuen Endpunkt benutzen:
POST https://api.oilfox.io/v3/login
Content-Type: application/json

{"email":"email@host", "password":"********"}

In der Antwort darauf erhalten Sie Ihren "access_token", der 15 Minuten lang gültig ist und mit dem alle bisherigen Anfragen getätigt werden können. Die Gültigkeitsdauer wird u.A. auch im Token gespeichert (zum decodieren siehe https://jwt.io/).
Verwendet wird er in jeder weiteren Anfrage (z.B. beim GET https://api.oilfox.io/v3/user/summary) im Authorization-Header:
Authorization: Bearer eyJ0eXAiO...

Außerdem erhalten Sie beim Login einen "refresh_token", mit dem Sie einen neuen access_token abrufen können, ohne dass Sie das Passwort des Nutzers im Klartext speichern und verwenden müssen. Der refresh_token ist 30 Tage lang gültig, bis er einmal benutzt wird. Damit erhalten Sie ein neues token-Paar:
POST https://api.oilfox.io/v3/token
Content-Type: application/x-www-form-urlencoded


refresh_token=eyJ0eXAiO...


Noch eine Bitte: Wenn Sie als User-Agent den Namen Ihres Plugins setzen (z.B. ioBroker.oilfox), fällt es uns leichter die Anfragen von anderen Clients zu unterscheiden und Probleme leichter zu erkennen. 

Viele Grüße,

Ihr OilFox Team

**Comment by jogibear9988** [comment]
hab ich auch bekommen, fixe es am WE

**Comment by jogibear9988** [comment]
fixed

**Comment by jogibear9988** [comment]
@Truwor81 danke nochmals für die ganzen hinweise...
Hat sich ja nicht viel geändert, außer wo ich das Token bekomme und wie ich es nutze.
P.S. der UserAgent ist nun drin

**Comment by Truwor81** [comment]
@jogibear9988 Gerne! Und vielen Dank für die schnelle Anpassung. Ich bin ja immer wieder froh, dass es Leute gibt, die es mir durch ihren Einsatz ermöglichen, viele unterschiedliche Geräte in mein SmartHome einzubinden!

**Comment by peoples0815** [comment]
Auch wenn das hier schon geschlossen ist mal die Frage ob das bei euch funktioniert?

Ich bekomme zwar den Fehler nicht mehr dass die Verbindung nicht funktioniert, aber Werte unter metering werden auch nicht übertragen.

**Comment by jogibear9988** [comment]
gibts fehler im log? ansonsten neuen issue aufmachen...

**Comment by jogibear9988** [comment]
und logausgaben posten

**Comment by jogibear9988** [comment]
hast auch aktualisier auf 2.0.1?

**Comment by juettra** [comment]
Erst mal vielen Dank für Euren tollen Einsatz. Allerdings geht es mir auch wie Jochen. Keine Fehlermeldungen im Log, aber auch keine Daten in den Objekten. In den Infos gibt es einen State „Error“, der zeigt 401 an. Anbei Bilder vom Log und den Objekten ...
![9CE85511-DB91-4F08-9A9E-9BC66AF437CA](https://user-images.githubusercontent.com/57261934/69485644-a9587b00-0e42-11ea-88e6-f397fad3dd2e.jpeg)
![A935ECE9-DEAA-4256-AABA-5FD4EDE5CE2D](https://user-images.githubusercontent.com/57261934/69485645-a9f11180-0e42-11ea-81e9-05410626c066.jpeg)

**Comment by juettra** [comment]
Noch eine Frage: wie updated man denn richtig auf die 2.0.1? Über die normale Adapter Funktion von ioBroker installiert er immer die 0.5.0 und ich mache dann einen „npm install iobroker.oilfox@2.0.1“. Zumindest im Log sagt er dann, dass er die 2.0.1 benutzt ...

**Comment by kwoneGitHub** [comment]
wenn 2.0.1 angezeigt wird, dann hast du alles richtig gemacht
da hilft nur abwarten!
oder CRON-Zeit der Instanz ändern!
da Oilfox nur 1 x am Tag messdaten erfasst

**Comment by signalblau** [comment]
> Noch eine Frage: wie updated man denn richtig auf die 2.0.1? Über die normale Adapter Funktion von ioBroker installiert er immer die 0.5.0 und ich mache dann einen „npm install iobroker.oilfox@2.0.1“. Zumindest im Log sagt er dann, dass er die 2.0.1 benutzt ...

Hey Leute könnt ihr mir helfen was genau ich da tun muss um oilfox2.0.1 auf meinem ioBroker zu bringen. Ich bin leider nicht so fit was die Komandos an geht und  bekomme mit „npm install iobroker.oilfox@2.0.1“ kein Erfolg. Würd mich freuen wenn ihr es mir erklären könntet. Ich habe leider nur die 0.0.5 Instanz von Oilfox installiert bekommen. Gruß Michi
