### ISSUE TITLE
Keine Daten unter Metering nach Update

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.oilfox#29]
gibts fehler im log? ansonsten neuen issue aufmachen...

_Originally posted by @jogibear9988 in https://github.com/iobroker-community-adapters/ioBroker.oilfox/issues/28#issuecomment-557832719_

- Es gibt Augenscheinlich keine Fehler im Log, auf Grund der vielen persönlichen Daten in Klartext möchte ich den Debuglog jedoch hier nicht Posten.
Kann diesen jedoch gerne zumailen!

**Comment by jogibear9988** [comment]
dann schick mir ne email.

**Comment by peoples0815** [comment]
Hab ich dir auf deine hier hinterlegte Mail geschickt

**Comment by juettra** [comment]
bei mir ist auch noch das gleiche Problem, auch nach über einem Tag Wartezeit. Anbei die Log-Ausgaben und Screenshots der Objekte im ioBroker. Ich kann wirklich nichts finden. Habe auch schon mehrfach den Adapter gelöscht und neu installiert. Die Daten unter Info findet er allerdings korrekterweise ...

[iobroker.2019-11-24.pdf](https://github.com/iobroker-community-adapters/ioBroker.oilfox/files/3883956/iobroker.2019-11-24.pdf)
<img width="1838" alt="Bildschirmfoto 2019-11-24 um 18 44 08" src="https://user-images.githubusercontent.com/57261934/69498849-99957100-0eec-11ea-8e9b-6a0c7597c5c3.png">
<img width="1823" alt="Bildschirmfoto 2019-11-24 um 18 45 01" src="https://user-images.githubusercontent.com/57261934/69498854-9f8b5200-0eec-11ea-95c1-f62f7e2142af.png">

**Comment by jogibear9988** [comment]
könnt ihr den github stand mal probieren?

**Comment by juettra** [comment]
meinst Du, die Dateien von dort aus downloaden und installieren? Dort ist aber auch die 2.0.1 Hinterlegt, oder?

Gruß

Ralf Juettner

**Comment by jogibear9988** [comment]
die version hab ich noch nicht angepasst, das mach ich wenn der fix funzt

**Comment by jogibear9988** [comment]
einfach über das github symbol vom repo installieren

**Comment by juettra** [comment]
Erkläre mal bitte. Weiß gerade nicht was Du meinst

**Comment by juettra** [comment]
ich habe jetzt einfach mal alles vom Github kopiert und über das iobroker/node-modules/iobroker.oilfox Verzeichnis drüberkopiert. Leider keine Änderung ...

**Comment by peoples0815** [comment]
Hab den Fix drüber laufen lassen leider keine Änderung.
Daten werden in der Debugansicht weiterhin schön angezeigt jedoch nicht in die Datenpunkte übernommen.

**Comment by jogibear9988** [comment]
nun sollte es gehen

**Comment by jogibear9988** [comment]
updaten

**Comment by peoples0815** [comment]
Bei mir gehts, tausend Dank!

**Comment by juettra** [comment]
bei mir geht es auch, allerdings nur einer meiner zwei eingesetzten Oilfoxe. Ich habe einen (oilfox.0.devices.0) bei dem das metering korrekt gefüllt wurde. Der zweite (oilfox.0.devices.1) ist weiterhin leer. Komischerweise sind die Daten, die früher unter device.1 waren jetzt unter device.0

**Comment by jogibear9988** [comment]
juretta, lösch mal die id beim zweiten. die müsste jetzt gleich der ersten sein. oder lösch nochmal alle signale

**Comment by juettra** [comment]
meinst Du mit "Signale" die objects? Ich hatte den Adapter komplett gelöscht und vor 45 Minuten neu installiert. Dabei hat er alles neu angelegt. Das Ergebnis ist aber das gleiche (Info korrekt gefüllt, device.0 korrekt gefüllt, device.1 leer). Bei der Gelegenheit habe ich festgestellt, dass im Log keine Fehlermeldung kommt wenn man ein falsches Password eingibt (hatte ich bewusst gemacht).

Eine Frage noch: wie kommt man denn an das Debüt-Log von dem peoples0815 spricht?

Viele Grüße

Ralf

**Comment by juettra** [comment]
würde es Dir helfen, wenn ich Dir kurzfristig Zugriff auf meinen Oilfox Account gebe? Ich weiß ja nicht, ob Du selber mehrere Foxe im Einsatz hast.

**Comment by jogibear9988** [comment]
du kannst unter instanzen den log level des adapters einstellen.

stell den mal von info auf silly

ich kümmere mich am donnerstag drum

**Comment by juettra** [comment]
Aha, again what learned :-)
Im Silly Log kann ich sehen, dass er im Datenblock die Werte beider Foxe ausliest. Zuerst die Zisterne, dann den Öltank. In die objects schreibt er dann aber nur die Werte vom zweiten Oilfox (Öltank) unter devices.0
Objekte unter devices.1 werden angelegt aber nicht geschrieben.
Vielleicht hilf Dir das. Wie gesagt, wenn hilfreich kann ich Dir temporär meinen Oilfox Zugang geben.

Vielen Dank aber für Deine tolle Unterstützung !!!

Ralf

**Comment by jogibear9988** [comment]
häng mal das log bitte an.

**Comment by jogibear9988** [comment]
und ein screenshot der objekte

**Comment by juettra** [comment]
Hier ist der Auszug aus dem Silly-Log und 2 Screenshots für die Objekte von Device.0 und Device.1

Nochmal: falls es für Dich einfacher ist gebe ich Dir mein temp. Passwort

[ioBroker-OilFox-Log.txt](https://github.com/iobroker-community-adapters/ioBroker.oilfox/files/3908547/ioBroker-OilFox-Log.txt)
<img width="1709" alt="Bildschirmfoto 1" src="https://user-images.githubusercontent.com/57261934/69918160-db836180-146e-11ea-8840-886336b93252.png">
<img width="1639" alt="Bildschirmfoto 2" src="https://user-images.githubusercontent.com/57261934/69918164-e2aa6f80-146e-11ea-84b3-8bcc1e91e271.png">

**Comment by juettra** [comment]
sind die Daten ok - kannst Du da was mit anfangen?

**Comment by juettra** [comment]
Hallo jogibear9988,

konntest Du was anfangen mit den Daten und meinst Du, dass Du das Problem lösen kannst? Ich wäre endlos dankbar.

Gruß juettra

**Comment by juettra** [comment]
Ich fürchte, der Zugriff auf die Oilfox API geht seit ein paar Stunden generell wieder nicht mehr. Unabhängig von dem Problem mit den mehreren Oilfoxen.

**Comment by peoples0815** [comment]
Ich denke das ist ein generelles Oilfox Problem, denn meine Handy App bekommt auch keine Verbindung

**Comment by juettra** [comment]
Stimmt. Aber jetzt gehts wieder.

**Comment by jogibear9988** [comment]
sorry hab das voll vergessen...
schau das ich nächste woche drum kümmere

**Comment by juettra** [comment]
das wäre super jogibaer9988. Wenn Du was brauchst bitte melde Dich.

**Comment by juettra** [comment]
Hallo Jogibear,
ich Hofe es geht Dir gut. Denkst Du, dass Du den Oilfox Adapter vielleicht doch noch hinbekommst? Ich wäre endlos dankbar.

Gruß

Ralf

**Comment by jogibear9988** [comment]
sorry das ich so lange keine zeit hatte....
aber ich kann den fehler nicht nachvollziehen.
wenn dann muss ich echt mal bei dir drauf.
hast da aber auch den letzten github stand probiert?

**Comment by juettra** [comment]
Danke fürs Feedback. Ich habe die 2.1.0 drauf. Ich schaue nochmal auf Github, aber das ist denke ich die letzte Variante, oder?

**Comment by juettra** [comment]
Hallo Jochen,
Ich habe jetzt eine komplett neue ioBroker Installation gemacht und nur den Oilfox installiert. Erst über die Adapter die latest stable 0.0.5 und dann mit "npm i iobroker.oilfox@2.1.0 die neueste Version upgedated. Ist das so richtig? 
Leider ist das Ergebnis noch genauso wie bisher. Wenn ich "silly" logge sehe ich Daten von beiden Oilfoxen, aber in den Objects ist der zweite bei metering.0 und bei metering.1 ist nichts drin.
Vielleicht wäre es tatsächlich am besten, Du hättest mal meine Oilfox Zugangsdaten zum selber schauen.

Viele Grüße

Ralf

**Comment by jogibear9988** [comment]
okay, schick mir mal deine daten, dann schau ichs mir die kommende woche mal an.

**Comment by jogibear9988** [comment]
@juettra kommando zurück, schau mal obs jetzt geht. da hat @wuzlwuz einen pull req. gemacht der es fixen sollte

**Comment by juettra** [comment]
muss ich irgendwas updated/neu installieren?

**Comment by jogibear9988** [comment]
ja, von github neu installieren

**Comment by juettra** [comment]
Habe jetzt npm install iobroker.oilfox gemacht. Hoffe, das ist richtig. Mal sehen in 10 Minuten ....
Falls das nicht geholfen hat: wie lasse ich Dir die Zugangsdaten am besten zukommen?

**Comment by juettra** [comment]
Keine Änderung ... leider

**Comment by jogibear9988** [comment]
nein, du musst von github installieren.

**Comment by juettra** [comment]
Es funktioniert !!!! Tausend Dank. Beide Oilfoxe werden jetzt korrekt abgefragt und die Objects richtig gefüllt. Super und danke nochmals.

Da ich kein GitHub Spezialist bin war ich mir nicht sicher, wie ich "aus dem GitHub installieren" muß/kann. Habe daher einfach die main.js aus deinem Master repository in mein iobroker.oilfox Verzeichnis kopiert und das hat funktioniert (main.js war die einzige Datei mit einem neueren Datum ...). 

Falls Du Zeit hast, einem Dummy kurz zu erklären, wie das richtigerweise aus dem GitHub installiert wird wäre ich noch dankbarer. Wird evtl. bei kommenden Updates wieder benötigt.

Tausend Dank

Ralf
