### ISSUE TITLE
Kleiner Verbesserungsvorschlag

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.oilfox#3]
Hi,
dein Adapter läuft super! Ein kleiner Verbesserungsvorschlag, man könnte noch das Passwort maskieren dass es nicht in Klartext steht.
Kann dir dazu nen Pullrequest schreiben wenn du es nicht selbst machen möchtest

**Comment by jogibear9988** [comment]
wenn du lust hast, gerne. ;-)

**Comment by foxriver76** [comment]
Am Besten wäre es, wenn du das Passwort auch verschlüsselt speicherst -> siehe https://github.com/Apollon77/ioBroker.alexa2/blob/ce2c19f46960b4a3386cc0cfc30ed2e46f25eea6/admin/index_m.html#L19 ;-)

**Comment by foxriver76** [comment]
Der Aufwand beschränkt sich auf Copy/Paste, das Secret ist je Installation unterschiedlich. Andere Adapter können aktuell trotzallem darauf zugreifen, jedoch müsste man das schon mutwillig tun, um es zu entschlüssen mit der Funktion. Ab js-c 2.0.0 o 1.6.0 was eben zu erst kommt (https://github.com/ioBroker/ioBroker.js-controller/pull/287) wird das was du im letzten Kommentar erwähnt hast möglich sein. 

Das Problem ist, dass es u.a schon vorkam, dass Adapter einfach alle objectchanges geloggt haben und dann eben ein Passwort im Klartext im Log war, was dem User zu Recht ein Gefühl von Unsicherheit vermittelt. (siehe z. B. https://github.com/jensweigele/ioBroker.yahka/issues/53 )

**Comment by jogibear9988** [comment]
@foxriver76 wann ist denn damit zu rechnen?

**Comment by foxriver76** [comment]
Schwer zu sagen, gibt noch einiges zu tun https://github.com/ioBroker/ioBroker.js-controller/projects/1 ;-)

**Comment by jogibear9988** [comment]
reicht es nicht das passwort einfach mit input type=password zu verstecken?

jeder der zugriff auf die config oberfläche hat kann sich sonst ja eh mit F12 das secret holen und dadurch auch das PWD.

Wenn der neue Controller dann da ist baue ich das um.

SOnst muss ich jetzt noch das laden des secretcs etc einbauen, obwohl man bei oilfox mit dem pwd nix machen kann!

**Comment by foxriver76** [comment]
Klar, ist kein Zwang. ;-)

**Comment by jogibear9988** [comment]
passwort ist ert mal maskiert (im master, npm folgt)
