### ISSUE TITLE
Das Object Oilfox wird nicht angelegt

### ISSUE THREAD

**Issue by gammelgul** [iobroker-community-adapters/ioBroker.oilfox#30]
Hallo, habe diese Woche den Oilfox bekommen und aktiviert.  
Dann habe ich das Modul im iobroker aktiviert. Bei mir wird allerdings nicht das Objekt oilfox angelegt.
Habe das Modul schon mehrfach neu installiert, leider ohne Erfolg. Wo könnte mein Problem sein.
Ich habe die aktuelle Version 0.0.5 installiert.

Das ist die Fehlermeldung bei Abruf der Daten:
2019-11-30 16:47:02.793 | error | (736) SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.tokenRequestResult.on (/opt/iobroker/node_modules/iobroker.oilfox/main.js:64:27)
-- | -- | --
oilfox.0 | 2019-11-30 16:47:02.792 | error | (736) uncaught exception: Unexpected token < in JSON at position 0

**Comment by jogibear9988** [comment]
0.5 ist zu alt.
du musst auf die unstable paketquellen wechseln
ich muss aber die nächste woch noch was fixen

**Comment by gammelgul** [comment]
Hallo, danke, hat nun geklappt. 
Ist das Problem, welches du fixen willst, der Wert bei "tankVolume", dort steht bei mir der selbe Wert, wie bei "tankUsableVolume"  drin?
Ich vermute, der erste Wert ist der gemessene Wert.

**Comment by jogibear9988** [comment]
nö, da will ich nix fixen.

da nehm ich die werte die ich geschickt bekomme, da kann ich eh nix fixen.

du musst unter metering/liters schauen
