### ISSUE TITLE
Adapter aktualisiert keine Daten mehr

### ISSUE THREAD

**Issue by Zandrial** [iobroker-community-adapters/ioBroker.oilfox#36]
Seit kurzem zieht der Adapter keine neuen Daten mehr.
Ich habe mal die Version von Github aufgespielt aber das brachte keine Verbesserung.
Logging hab ich auf silly gestellt aber die einzige Ausgabe die erscheint ist:

host.ioBroker | 2020-02-23 08:50:00.010 | warn | instance system.adapter.oilfox.0 already running with pid 4335

**Comment by jogibear9988** [comment]
ist das immer noch so?

**Comment by Zandrial** [comment]
Hallo,
seit kurzer Zeit geht es wieder. Danke.
