### ISSUE TITLE
Update stable version in repo to 2.1.0

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.oilfox#38]
# Think about update stable version to 2.1.0
**Version**: stable=**0.0.5** (419 days old) => latest=**2.1.0** (99 days old)
**Installs**: stable=**55** (42.64%), latest=**59** (45.74%), total=**129**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L907)

**Comment by inidona** [comment]
+1
