### ISSUE TITLE
Seit 27.08.2020 wieder Fehler beim Daten holen

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.oilfox#41]
Hi, 

wie es scheint, wurde mit dem Update der Android-App wieder etwas geändert, da bei dem Adapter wieder Fehler beim Daten holen zurück gemeldet werden.

**2020-08-28 18:16:01.345 - debug: oilfox.1 (30047) recieved chunk2:
HTTP Status 404 – Not Found
2020-08-28 18:16:01.345 - debug: oilfox.1 (30047) recieved data 2:
HTTP Status 404 – Not Found**

Hier mal der ganze Log:
- 2020-08-28 18:16:01.061 - info: oilfox.1 (30047) starting. Version 2.1.0 in /opt/iobroker/node_modules/iobroker.oilfox, node: v12.16.3, js-controller: 3.1.6
- 2020-08-28 18:16:01.095 - debug: oilfox.1 (30047) adapter.on-ready: << READY >>
- 2020-08-28 18:16:01.096 - debug: oilfox.1 (30047) adapter.main: << MAIN >>
- 2020-08-28 18:16:01.117 - debug: oilfox.1 (30047) send data: {"email":"XXXXXXXXX","password":"XXXXXXXXXXX"}
- 2020-08-28 18:16:01.284 - debug: oilfox.1 (30047) recieved chunk: {"token_type":"Bearer","access_token":"xxx"}
- 2020-08-28 18:16:01.285 - debug: oilfox.1 (30047) recieved data: {"token_type":"Bearer","access_token":"xxx"}
- 2020-08-28 18:16:01.345 - debug: oilfox.1 (30047) recieved chunk2:
- HTTP Status 404 – Not Found
- 2020-08-28 18:16:01.345 - debug: oilfox.1 (30047) recieved data 2:
- HTTP Status 404 – Not Found
- 2020-08-28 18:16:01.346 - error: oilfox.1 (30047) uncaught exception: Unexpected token < in JSON at position 0
- 2020-08-28 18:16:01.357 - error: oilfox.1 (30047) SyntaxError: Unexpected token < in JSON at position 0
- at JSON.parse ()
- at IncomingMessage. (/opt/iobroker/node_modules/iobroker.oilfox/main.js:75:31)
- at IncomingMessage.emit (events.js:322:22)
- at endReadableNT (_stream_readable.js:1187:12)
- at processTicksAndRejections (internal/process/task_queues.js:84:21)
- 2020-08-28 18:16:01.864 - info: oilfox.1 (30047) terminating
- 2020-08-28 18:16:01.866 - info: oilfox.1 (30047) Terminated (NO_ERROR): Without reason

**Comment by kortos** [comment]
Ja, ich habe das selbe Problem.

**Comment by huettmasterTB** [comment]
Jap.Bei mir das gleiche...

**Comment by dolenec** [comment]
Yes.. In Node-Red which I'm using to parse cURL for Home Assistant I got the same error.
Today I write e-mail to oilfox.io.. If anybody has new url or something please report it..

**Comment by Kubby66** [comment]
Same....

**Comment by dolenec** [comment]
I will try to crack what is sended to web portal and make bypass so that I will collect data also locally..

**Comment by peoples0815** [comment]
> 
> 
> I will try to crack what is sended to web portal and make bypass so that I will collect data also locally..

I think this would be the best way, because obviously oilfox is not interested in their products being integrated into other systems. Otherwise  there would be an official api available and the support would be better

**Comment by bazidibavaria** [comment]
#43

**Comment by Winni66** [comment]
Great, thanks a lot for sharing...
Do you have any information about former "chartData" to get current price information in addition?

**Comment by peoples0815** [comment]
Seems, that the connection - Error is fixed, but metering ist not updated on my iobroker

**Comment by Winni66** [comment]
I don't have any experience with iobroker, but JSON information has also changed. "metering" is now called "lastMetering".
I hope this information can help!

**Comment by dolenec** [comment]
Can you provide complete JSON?

**Comment by Winni66** [comment]
There are other changes, but I didn't investigate, "chartData" doesn't exist anymore, perhaps you need another URL and "partner" has moved and is now called "partners".  As soon as you can connect and request data you will be able to inspect JSON to check whether the information you will need is still available. I was using chartData for Price information which isn't available anymore in "summary"
