### ISSUE TITLE
Oilfox Adapter zeigt Fehler im Log und bekommt keine Daten

### ISSUE THREAD

**Issue by cc-gismo** [iobroker-community-adapters/ioBroker.oilfox#42]
![2020-09-03 08_12_56-logs - ioBroker](https://user-images.githubusercontent.com/70684769/92078069-f8621200-edbd-11ea-97fb-da828d1543f7.png)
Das problem besteit mit der 0.0.5 und der 2.3.0

oilfox.0 | 2020-09-03 08:00:02.119 | info | (26355) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
oilfox.0 | 2020-09-03 08:00:02.118 | info | (26355) terminating
oilfox.0 | 2020-09-03 08:00:01.612 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
oilfox.0 | 2020-09-03 08:00:01.612 | error | at endReadableNT (_stream_readable.js:1220:12)
oilfox.0 | 2020-09-03 08:00:01.612 | error | at IncomingMessage.emit (events.js:327:22)
oilfox.0 | 2020-09-03 08:00:01.612 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:75:31)
oilfox.0 | 2020-09-03 08:00:01.612 | error | at JSON.parse (<anonymous>)
oilfox.0 | 2020-09-03 08:00:01.612 | error | (26355) SyntaxError: Unexpected token < in JSON at position 0
oilfox.0 | 2020-09-03 08:00:01.610 | error | (26355) uncaught exception: Unexpected token < in JSON at position 0
oilfox.0 | 2020-09-03 08:00:01.121 | info | (26355) starting. Version 2.3.0 in /opt/iobroker/node_modules/iobroker.oilfox, node: v12.18.3, js-controller: 3.1.6

**Comment by peoples0815** [comment]
Das hat nichts mit der Adapterversion zu tun sondern damit dass Oilfox irgendwas verändert hat.

Das Issue vor deinem geht um das gleiche Thema:
https://github.com/iobroker-community-adapters/ioBroker.oilfox/issues/41

**Comment by jogibear9988** [comment]
kann jemand bei oulfox nachfrage? dann kann ich es fixen.
hab aber gerade keine zeit mich drum zu kümmern

**Comment by jogibear9988** [comment]
vlt. kann ja jemand nochmal kontakt aufnehmen, in dem ticket stehen die daten

https://github.com/iobroker-community-adapters/ioBroker.oilfox/issues/28

**Comment by peoples0815** [comment]
> 
> 
> vlt. kann ja jemand nochmal kontakt aufnehmen, in dem ticket stehen die daten
> 
> #28

Ich habe denen eine Mail geschrieben, mal schauen ob Sie dieses mal schneller sind als das vorherige

**Comment by peoples0815** [comment]
Antwort von Heute:

Hallo Herr :-),

ich habe diese Thematik bei unseren Programmieren platziert. Sobald ich diesbezüglich eine Rückmeldung habe, werde ich mich bei Ihnen melden.

Viele Grüße
Das OilFox Team aus München

Ihr Team vom Partner Support

**Comment by MiGoller** [comment]
Warten wir es mal ab.

**Comment by bazidibavaria** [comment]
Issue already exists => https://github.com/iobroker-community-adapters/ioBroker.oilfox/issues/41

**Comment by juettra** [comment]
Ich hoffe mit ....

**Comment by jogibear9988** [comment]
geht hoffentlich wieder.
bugfix von @bazidibavaria

**Comment by peoples0815** [comment]
noch nicht, das metering wird noch nicht geschrieben / aktuallisiert

**Comment by el-Presi** [comment]
und wie kommt man an diesen bugfix????
