### ISSUE TITLE
Error im Log seit V0.0.3

### ISSUE THREAD

**Issue by peoples0815** [iobroker-community-adapters/ioBroker.oilfox#5]
Hi,
habe gerade das Update gemacht und bekomme (bei mir) folgenden Fehler im LOG:

2019-01-08 21:00:00.391 - error: host.iobroker-produktiv-system instance system.adapter.oilfox.0 terminated with code 1 ()

auch wenn ich auf debug stelle bekomme ich keine weiteren Angaben.

Nach dem Downgrade auf 0.0.2 ist der Fehler (bei mir)weg

**Comment by jogibear9988** [comment]
Adapter komplett gelöscht?

Ich habe in 0.0.3 den adapter auf scheduled umgestellt, da es nicht nötig ist das da ein dienst im hintergund läuft. Daher nochmal komplett entfernen!

**Comment by peoples0815** [comment]
habe ich gerade gemacht, gleicher Fehler im Log

**Comment by jogibear9988** [comment]
Hast du denn unter Instanzen bei der Spaklte Zeitplanung einen Wert im Oilfox Adapter?

**Comment by jogibear9988** [comment]
scheint bei mir nun auch der fall zu sein. ich schau es nach und behebs ;-)

**Comment by tunneltruppe** [comment]
...erstmal DANKE für den Baustein!!!! Ja leider geht es bei mir auch nicht mehr....
..bin mal gespannt...

**Comment by jogibear9988** [comment]
gefixt
