### ISSUE TITLE
Update States with multiple Sensors ends up in endless loop

### ISSUE THREAD

**Issue by danyial** [iobroker-community-adapters/ioBroker.oilfox#58]
https://github.com/iobroker-community-adapters/ioBroker.oilfox/blob/41d5a680da7d2d5b3650ca369cafc528cbe23cee/main.js#L179

We need a `break;` after the line.

**Comment by jogibear9988** [comment]
can you create a pull request?

**Comment by jogibear9988** [comment]
i think the whole code is wrong

**Comment by jogibear9988** [comment]
I created a fix

**Comment by jogibear9988** [comment]
should be fixed
