### ISSUE TITLE
Adapter ist rot seit heute 12.01.2019

### ISSUE THREAD

**Issue by mister2212** [iobroker-community-adapters/ioBroker.oilfox#6]
Seit heute ist der oilfox adapter rot und funktioniert nicht mehr.

hier der log vom iobroker:
host.debianiobroker | 2019-01-12 19:54:45.886 | error | instance system.adapter.oilfox.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-01-12 19:54:45.886 | error | by controller[0]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Caught | 2019-01-12 19:54:45.886 | error | by controller[0]:     at _combinedTickCallback (internal/process/next_tick.js:139:11)
Caught | 2019-01-12 19:54:45.886 | error | by controller[0]:     at endReadableNT (_stream_readable.js:1064:12)
Caught | 2019-01-12 19:54:45.886 | error | by controller[0]:     at IncomingMessage.emit (events.js:208:7)
Caught | 2019-01-12 19:54:45.885 | error | by controller[0]:     at emitNone (events.js:111:20)
Caught | 2019-01-12 19:54:45.885 | error | by controller[0]:     at IncomingMessage.summaryRequestResult.on (/opt/iobroker/node_modules/iobroker.oilfox/main.js:85:14)
Caught | 2019-01-12 19:54:45.885 | error | by controller[0]: TypeError: adapter.stop is not a function
oilfox.0 | 2019-01-12 19:54:45.870 | info | terminating
oilfox.0 | 2019-01-12 19:54:45.365 | error | at process._tickCallback (internal/process/next_tick.js:181:9)
oilfox.0 | 2019-01-12 19:54:45.365 | error | at _combinedTickCallback (internal/process/next_tick.js:139:11)
oilfox.0 | 2019-01-12 19:54:45.365 | error | at endReadableNT (_stream_readable.js:1064:12)
oilfox.0 | 2019-01-12 19:54:45.365 | error | at IncomingMessage.emit (events.js:208:7)
oilfox.0 | 2019-01-12 19:54:45.365 | error | at emitNone (events.js:111:20)
oilfox.0 | 2019-01-12 19:54:45.365 | error | at IncomingMessage.summaryRequestResult.on (/opt/iobroker/node_modules/iobroker.oilfox/main.js:85:14)
oilfox.0 | 2019-01-12 19:54:45.365 | error | TypeError: adapter.stop is not a function
oilfox.0 | 2019-01-12 19:54:45.365 | error | uncaught exception: adapter.stop is not a function
oilfox.0 | 2019-01-12 19:54:44.596 | info | starting. Version 0.0.6 in /opt/iobroker/node_modules/iobroker.oilfox, node: v8.13.0
host.debianiobroker | 2019-01-12 19:54:44.283 | info | instance system.adapter.oilfox.0 started with pid 16523

**Comment by jogibear9988** [comment]
hast du aktualisiert?
denke du musst die instanz nochmal komplett löschen. da ich oilfox von einem dienst auf einen geschedulten adapter umgestellt habe

**Comment by mister2212** [comment]
so habe nochmal alles gelöscht jetzt gehts wieder. keine ahnung was los war. dnake dir nochmal Jogi
