### ISSUE TITLE
uncaught exception: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by 90er** [iobroker-community-adapters/ioBroker.oilfox#61]
Hello,

first of all: thanks for your work.

I'm running ioBroker 4.2.1 and your adapter in version 0.0.5. I use the OilFox 2 and be able to use the OilFox App within iOS.

I created an instance and filled in the E-Mail and Password, which i'm also using in the iOS App.

When the cron runs, i get the following info, warn and error in the Logs:

```
oilfox.0 | 2021-06-29 15:20:03.491 | warn | (32560) Terminated (UNCAUGHT_EXCEPTION): Without reason
oilfox.0 | 2021-06-29 15:20:03.486 | info | (32560) terminating
oilfox.0 | 2021-06-29 15:20:02.946 | error | (32560) Unexpected token < in JSON at position 0
oilfox.0 | 2021-06-29 15:20:02.945 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
oilfox.0 | 2021-06-29 15:20:02.945 | error | at endReadableNT (_stream_readable.js:1241:12)
oilfox.0 | 2021-06-29 15:20:02.945 | error | at IncomingMessage.emit (events.js:326:22)
oilfox.0 | 2021-06-29 15:20:02.945 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:64:27)
oilfox.0 | 2021-06-29 15:20:02.945 | error | at JSON.parse (<anonymous>)
oilfox.0 | 2021-06-29 15:20:02.945 | error | (32560) SyntaxError: Unexpected token < in JSON at position 0
oilfox.0 | 2021-06-29 15:20:02.941 | error | (32560) uncaught exception: Unexpected token < in JSON at position 0
```

Could you please help me fix this?

Thanks

**Comment by Schlumpel** [comment]
i share the same fate. Allegedly you should be able to install up to version 2 on the adapter side. I am only ever offered version 0.5. Unfortunately, I am unable to solve the problem on my own

**Comment by el-Presi** [comment]
Same here. Version 2.1.0 does also not work here.. but how to install 3.1.0 ?

**Comment by 90er** [comment]
> Same here. Version 2.1.0 does also not work here.. but how to install 3.1.0 ?

I just updated my iobroker:

oilfox.0 | 2021-08-05 12:50:07.767 | warn | (17335) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
oilfox.0 | 2021-08-05 12:50:07.761 | info | (17335) terminating
oilfox.0 | 2021-08-05 12:50:07.241 | error | (17335) Unexpected token < in JSON at position 0
oilfox.0 | 2021-08-05 12:50:07.239 | error | at processTicksAndRejections (internal/process/task_queues.js:84:21)
oilfox.0 | 2021-08-05 12:50:07.239 | error | at endReadableNT (_stream_readable.js:1241:12)
oilfox.0 | 2021-08-05 12:50:07.239 | error | at IncomingMessage.emit (events.js:326:22)
oilfox.0 | 2021-08-05 12:50:07.239 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:64:27)
oilfox.0 | 2021-08-05 12:50:07.239 | error | at JSON.parse (<anonymous>)
oilfox.0 | 2021-08-05 12:50:07.239 | error | (17335) SyntaxError: Unexpected token < in JSON at position 0
oilfox.0 | 2021-08-05 12:50:07.234 | error | (17335) uncaught exception: Unexpected token < in JSON at position 0
oilfox.0 | 2021-08-05 12:50:06.914 | info | (17335) starting. Version 0.0.5 in /opt/iobroker/node_modules/iobroker.oilfox, node: v12.22.4, js-controller: 3.3.15

**Comment by 90er** [comment]
> Same here. Version 2.1.0 does also not work here.. but how to install 3.1.0 ?

I'm also on version 2.1.0. No update to version 3.1.0 available in ioBroker

**Comment by MarioSander** [comment]
läuft der Oilfox bei euch im IoBroker?  habe Version 3.1.0 drauf aber bekomme den adapter nicht grün bzw in den Objekten keine Daten.

**Comment by MeisterHoppel** [comment]
Dont work for me too. Always on 3.1.  Same issue. Hope they will fix it soon.
