### ISSUE TITLE
Announcement: New Customer-API for Community Projects

### ISSUE THREAD

**Issue by lhemala** [iobroker-community-adapters/ioBroker.oilfox#69]
Hi Community,

I'm from the FoxInsights development team. Among other things, we are responsible for the FoxMobile app (formerly OilFox App) and infrastructure.

We noticed that you use a legacy API of our app to import data into your system. Since this is an internal API and not meant to be used by others, there might be unannounced breaking changes. In fact, the version you are currently using will be shut down by **2022-03-01**.
As a replacement, we created an official customer API for you to use, which provides the same data. You can find the documentation in our GitHub repository [here](https://github.com/foxinsights/customer-api).
If you have further questions, please open a new discussion in our repository.

Thanks,
Lars

---

Hi Community,

Ich bin ein Mitglied vom FoxInsights-Entwickler-Team. Wir sind für die FoxMobile App (ehemals OilFox App) und Infrastruktur verantwortlich.

Uns ist aufgefallen, dass Ihr eine Legacy-API unserer App nutzt um Daten in euer System zu importieren. Nachdem es sich dabei um eine interne API handelt, die nicht für die Nutzung durch andere bestimmt ist, kann es zu jedem Zeitpunkt zu inkompatiblen Änderungen unsererseits kommen. Konkret wird die Version der API, die Ihr aktuell nutzt am **2022-03-01** abgeschaltet.
Als Ersatz haben wir eine offizielle Customer-API für euch erstellt, die dieselben Daten bereitstellt. Die Dokumentation find Ihr in unserem GitHub-Repository [hier](https://github.com/foxinsights/customer-api).
Falls Ihr weitere Fragen habt, erstellt bitte eine neue Diskussion in unserem Repository. Denkt bitte daran, eure Fragen auf englisch zu stellen, damit alle davon profitieren können.

Vielen Dank,
Lars

**Comment by jogibear9988** [comment]
fix via last pull
