### ISSUE TITLE
Oilfox Fehler

### ISSUE THREAD

**Issue by Rabenauer** [iobroker-community-adapters/ioBroker.oilfox#77]
Der Oilfox Adapter funktioniert nicht mehr, gibt es ein API Problem ?

![image](https://user-images.githubusercontent.com/102321465/159985234-3ad7fa8e-8995-47da-aa65-b96df04f1ab4.png)

**Comment by proper0912** [comment]
Hallo ich habe das selbe Problem

**Comment by MiGoller** [comment]
Leider kann ich den Fehler auch bestätigen:

```
2022-03-24 22:59:02.346 - info: oilfox.0 (1945) starting. Version 3.1.0 (non-npm: iobroker-community-adapters/ioBroker.oilfox#master) in /opt/iobroker/node_modules/iobroker.oilfox, node: v12.22.11, js-controller: 4.0.21
2022-03-24 22:59:02.731 - error: oilfox.0 (1945) uncaught exception: Unexpected token < in JSON at position 0
2022-03-24 22:59:02.733 - error: oilfox.0 (1945) SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse ()
at IncomingMessage. (/opt/iobroker/node_modules/iobroker.oilfox/main.js:65:27)
at IncomingMessage.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1241:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-03-24 22:59:02.734 - error: oilfox.0 (1945) Unexpected token < in JSON at position 0
2022-03-24 22:59:03.246 - info: oilfox.0 (1945) terminating
2022-03-24 22:59:03.249 - warn: oilfox.0 (1945) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-03-24 22:59:03.814 - error: host.iobroker instance system.adapter.oilfox.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

Sieht so aus, als würde der Fehler bei mir seit gestern auftreten.

**Comment by proper0912** [comment]
Ja bei mir auch, Grund ist die Firma Oilfox -> jetzt FoxInsights haben den API aufruf geändert und hier bei GitHub sogar eine Doku hinterlegt! [Github FoxInsights](https://github.com/foxinsights/customer-api) . Bin aber leider in der Hinsicht der https aufrufe mit javascript nicht so gut, um das mal schnell anzupassen!

**Comment by Schlumpel** [comment]
bin auch betroffen. Die wohl wichtigste Frage ist für mich: Wie geht es denn hier weiter? Den Dokulink von Foxinsights kann ich nicht verstehen. Wer hat denn diesen ursprünglichen Adapter "erstellt"? Wer versteht den diese für mich unverständlichen Programmieranweisungen? Schade, dass derartige Spontanitäten mir den Spaß an der Sache ioBroker verderben.
Aber okay, was solls. Bin halt einfach nur zu doof. 

VG
Schlumpel

host.iobrokersyno
2022-03-24 15:00:02.489	error	instance system.adapter.oilfox.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
oilfox.0
2022-03-24 15:00:01.962	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
oilfox.0
2022-03-24 15:00:01.961	info	terminating
oilfox.0
2022-03-24 15:00:01.455	error	Unexpected token < in JSON at position 0
oilfox.0
2022-03-24 15:00:01.454	error	SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:65:27) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
oilfox.0
2022-03-24 15:00:01.453	error	uncaught exception: Unexpected token < in JSON at position 0
oilfox.0
2022-03-24 15:00:01.192	info	starting. Version 3.1.0 (non-npm: iobroker-community-adapters/ioBroker.oilfox#master) in /opt/iobroker/node_modules/iobroker.oilfox, node: v14.19.0, js-controller: 4.0.21
host.iobrokersyno
2022-03-24 15:00:00.061	info	instance system.adapter.oilfox.0 started with pid 26420
javascript.0
2022-03-24 14:59:12.524	info	script.js.common.LoganTelegram: Following was sent to telegram: host.iobrokersyno instance system.adapter.oilfox.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
javascript.0
2022-03-24 14:59:11.494	info	script.js.common.LoganTelegram: Following was sent to telegram: oilfox.0 (26374) Unexpected token < in JSON at position 0
javascript.0
2022-03-24 14:59:11.493	info	script.js.common.LoganTelegram: Following was sent to telegram: oilfox.0 (26374) SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:65:27) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
javascript.0
2022-03-24 14:59:11.492	info	script.js.common.LoganTelegram: Following was sent to telegram: oilfox.0 (26374) uncaught exception: Unexpected token < in JSON at position 0
host.iobrokersyno
2022-03-24 14:59:02.521	error	instance system.adapter.oilfox.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
oilfox.0
2022-03-24 14:59:01.996	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason
ilfox.0
2022-03-24 14:59:01.995	info	terminating
oilfox.0
2022-03-24 14:59:01.488	error	Unexpected token < in JSON at position 0
oilfox.0
2022-03-24 14:59:01.488	error	SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.oilfox/main.js:65:27) at IncomingMessage.emit (events.js:412:35) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)
oilfox.0
2022-03-24 14:59:01.486	error	uncaught exception: Unexpected token < in JSON at position 0
oilfox.0
2022-03-24 14:59:01.110	info	starting. Version 3.1.0 (non-npm: iobroker-community-adapters/ioBroker.oilfox#master) in /opt/iobroker/node_modules/iobroker.oilfox, node: v14.19.0, js-controller: 4.0.21

**Comment by MiGoller** [comment]
> Ja bei mir auch, Grund ist die Firma Oilfox -> jetzt FoxInsights haben den API aufruf geändert und hier bei GitHub sogar eine Doku hinterlegt! [Github FoxInsights](https://github.com/foxinsights/customer-api) . Bin aber leider in der Hinsicht der https aufrufe mit javascript nicht so gut, um das mal schnell anzupassen!

Klasse, ich schaue mir das mal an. Heute wird das allerdings nichts. Ich gebe Euch Feedback.

**Comment by dywtglt** [comment]
Leider sind in der neuen API nicht alle Informationen wie früher (wie z. B. Füllhöhe in cm) abrufbar.

**Comment by dywtglt** [comment]
Ich hätte hier einen Flow für Redmatic anzubieten. Dieser wurde bereits auf die neue API angepasst. Vielleicht hilft es dem ein oder anderen:

`[{"id":"fca0ddaa.b033d","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b1dc4852.a0c2f8","type":"change","z":"fca0ddaa.b033d","name":"Befehl: Tokenabruf ","rules":[{"t":"set","p":"payload","pt":"msg","to":"{\"email\":\"email\",\"password\":\"password\"}","tot":"json"},{"t":"set","p":"headers","pt":"msg","to":"{\"Content-Type\":\"application/json\"}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":550,"y":80,"wires":[["e0675eaa.54666"]]},{"id":"d9be0529.abae78","type":"debug","z":"fca0ddaa.b033d","name":"curl","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":950,"y":80,"wires":[]},{"id":"e7021f1e.d9caa","type":"json","z":"fca0ddaa.b033d","name":"Token parsing","property":"payload","action":"","pretty":true,"x":360,"y":160,"wires":[["b4bf8469.f97448"]]},{"id":"676ac2b4.4624fc","type":"debug","z":"fca0ddaa.b033d","name":"Token","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":950,"y":160,"wires":[]},{"id":"b4bf8469.f97448","type":"change","z":"fca0ddaa.b033d","name":"Headers & Auth","rules":[{"t":"set","p":"headers","pt":"msg","to":"{\t  \"Authorization\" : payload.token_type & \" \" & payload.access_token,\t  \"Content-Type\" : \"application/json\"\t}","tot":"jsonata"},{"t":"delete","p":"payload","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":560,"y":160,"wires":[["676ac2b4.4624fc","e2b35c3d.1cfe3"]]},{"id":"a9d6c6f4.5dfd08","type":"debug","z":"fca0ddaa.b033d","name":"Summary","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":960,"y":220,"wires":[]},{"id":"1caba404.69245c","type":"json","z":"fca0ddaa.b033d","name":"Summary parsing","property":"payload","action":"","pretty":true,"x":570,"y":220,"wires":[["a9d6c6f4.5dfd08","b86b6775.c65df8"]]},{"id":"e0675eaa.54666","type":"www-request","z":"fca0ddaa.b033d","name":"Login","method":"POST","ret":"txt","url":"https://api.oilfox.io/customer-api/v1/login","follow-redirects":true,"persistent-http":true,"tls":"","x":750,"y":80,"wires":[["d9be0529.abae78","e7021f1e.d9caa"]]},{"id":"e2b35c3d.1cfe3","type":"www-request","z":"fca0ddaa.b033d","name":"Get Summary","method":"GET","ret":"txt","url":"https://api.oilfox.io/customer-api/v1/device","follow-redirects":true,"persistent-http":true,"tls":"","x":360,"y":220,"wires":[["1caba404.69245c"]]},{"id":"b86b6775.c65df8","type":"change","z":"fca0ddaa.b033d","name":"Assemble Attributes","rules":[{"t":"set","p":"attributes","pt":"msg","to":"payload.items[0]","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":380,"y":300,"wires":[["a6e6a0f4.09f25","e52bb049.4c3cb","6c2a7ce3.0c0854","c7d75e9f.fbddb","1cb02fb1.3b1e1","2578871c.28c9a8","af5e62b0.ffb18"]]},{"id":"6755c47b.b44f1c","type":"inject","z":"fca0ddaa.b033d","name":"Immer um 23 Uhr","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"00 23 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":350,"y":80,"wires":[["b1dc4852.a0c2f8"]]},{"id":"a6e6a0f4.09f25","type":"debug","z":"fca0ddaa.b033d","name":"Payload","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"attributes","targetType":"msg","statusVal":"","statusType":"auto","x":960,"y":300,"wires":[]},{"id":"e52bb049.4c3cb","type":"function","z":"fca0ddaa.b033d","name":"saveCurrentOilfoxData","func":"// Verbrauch berechnen\nglobal.set('cOilfoxConsumptionLiters', global.get('cOilfoxLiters')-msg.attributes.fillLevelQuantity);\n\n// Aktuelle Werte\nglobal.set('cOilfoxFillingPercentage', msg.attributes.fillLevelPercent);\nglobal.set('cOilfoxLiters', msg.attributes.fillLevelQuantity);\nglobal.set('cOilfoxBattery', msg.attributes.batteryLevel);\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":480,"y":900,"wires":[["c69b5eda.dbaf5"]]},{"id":"7ae98672.ce8498","type":"ui_gauge","z":"fca0ddaa.b033d","name":"Füllstand","group":"bffe7db2.1aa22","order":1,"width":0,"height":0,"gtype":"wave","title":"Liter von 3800l","label":"l","format":"{{value}}","min":"100","max":"3800","colors":["#df1111","#f1ca04","#2eb230"],"seg1":"","seg2":"","x":680,"y":540,"wires":[]},{"id":"6c2a7ce3.0c0854","type":"function","z":"fca0ddaa.b033d","name":"fillLevelQuantity","func":"msg.payload = msg.attributes.fillLevelQuantity;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":480,"y":540,"wires":[["7ae98672.ce8498"]]},{"id":"e41cbcd2.49853","type":"ui_gauge","z":"fca0ddaa.b033d","name":"Füllmenge (%)","group":"bffe7db2.1aa22","order":2,"width":0,"height":0,"gtype":"gage","title":"Füllmenge","label":"%","format":"{{value}}","min":"0","max":"100","colors":["#df1111","#f1ca04","#2eb230"],"seg1":"","seg2":"","x":700,"y":600,"wires":[]},{"id":"c7d75e9f.fbddb","type":"function","z":"fca0ddaa.b033d","name":"fillLevelPercent","func":"msg.payload = msg.attributes.fillLevelPercent;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":480,"y":600,"wires":[["e41cbcd2.49853"]]},{"id":"34cf442.0ac2bbc","type":"ui_text","z":"fca0ddaa.b033d","group":"bffe7db2.1aa22","order":4,"width":0,"height":0,"name":"","label":"Batterie Oilfox","format":"{{msg.payload}}","layout":"row-spread","x":700,"y":660,"wires":[]},{"id":"1cb02fb1.3b1e1","type":"function","z":"fca0ddaa.b033d","name":"batteryLevel","func":"msg.payload = msg.attributes.batteryLevel;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":470,"y":660,"wires":[["34cf442.0ac2bbc"]]},{"id":"9eaf3303.091ee","type":"ui_chart","z":"fca0ddaa.b033d","name":"","group":"bffe7db2.1aa22","order":6,"width":0,"height":0,"label":"Ölverbrauch und Durchschnittstemperatur","chartType":"line","legend":"true","xformat":"D/M","interpolate":"step","nodata":"Noch keine Daten verfügbar.","dot":true,"ymin":"","ymax":"","removeOlder":"21","removeOlderPoints":"","removeOlderUnit":"86400","cutout":0,"useOneColor":true,"useUTC":false,"colors":["#1f77b4","#f0333c","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"outputs":1,"useDifferentColor":false,"x":920,"y":980,"wires":[[]]},{"id":"35651d6f.bf1cc2","type":"function","z":"fca0ddaa.b033d","name":"","func":"var oil = {}\nvar weather = {}\n\noil.payload = global.get('cOilfoxConsumptionLiters');\noil.topic = 'Öltagesverbrauch (l)';\n\nweather.payload = msg.payload[0].tempc;\nweather.topic = 'Durchschnittstemperatur (°C)';\nreturn [oil, weather];","outputs":2,"noerr":0,"initialize":"","finalize":"","x":640,"y":980,"wires":[["abccaab0.b954e8","9eaf3303.091ee"],["abccaab0.b954e8","9eaf3303.091ee"]]},{"id":"c69b5eda.dbaf5","type":"http request","z":"fca0ddaa.b033d","name":"weatherdata","method":"GET","ret":"obj","paytoqs":"ignore","url":"https://urltoweathersite","tls":"","persist":false,"proxy":"","authType":"","x":470,"y":980,"wires":[["35651d6f.bf1cc2"]]},{"id":"abccaab0.b954e8","type":"debug","z":"fca0ddaa.b033d","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":860,"y":1120,"wires":[]},{"id":"31358dd.8621072","type":"ui_text","z":"fca0ddaa.b033d","group":"bffe7db2.1aa22","order":5,"width":0,"height":0,"name":"","label":"Aktuelle Messung:","format":"{{msg.payload}}","layout":"row-spread","x":710,"y":720,"wires":[]},{"id":"2578871c.28c9a8","type":"moment","z":"fca0ddaa.b033d","name":"currentMeteringAt","topic":"","input":"attributes.currentMeteringAt","inputType":"msg","inTz":"Europe/Paris","adjAmount":0,"adjType":"days","adjDir":"add","format":"DD.MM.YYYY HH:mm:ss","locale":"en-US","output":"payload","outputType":"msg","outTz":"Europe/Paris","x":490,"y":720,"wires":[["31358dd.8621072"]]},{"id":"d27119e8.633908","type":"inject","z":"fca0ddaa.b033d","name":"Clear chart manually","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"[]","payloadType":"json","x":860,"y":900,"wires":[["9eaf3303.091ee"]]},{"id":"af5e62b0.ffb18","type":"moment","z":"fca0ddaa.b033d","name":"nextMeteringAt","topic":"","input":"attributes.nextMeteringAt","inputType":"msg","inTz":"Europe/Paris","adjAmount":0,"adjType":"days","adjDir":"add","format":"DD.MM.YYYY HH:mm:ss","locale":"en-US","output":"payload","outputType":"msg","outTz":"Europe/Paris","x":480,"y":780,"wires":[["49d3e26a.af7b2c"]]},{"id":"49d3e26a.af7b2c","type":"ui_text","z":"fca0ddaa.b033d","group":"bffe7db2.1aa22","order":5,"width":0,"height":0,"name":"","label":"Nächste Messung:","format":"{{msg.payload}}","layout":"row-spread","x":710,"y":780,"wires":[]},{"id":"bffe7db2.1aa22","type":"ui_group","name":"Ölstand","tab":"26489ba2.e61f44","order":1,"disp":true,"width":"6","collapse":false},{"id":"26489ba2.e61f44","type":"ui_tab","name":"Heizung","icon":"dashboard","order":10,"disabled":false,"hidden":false}]`

**Comment by MiGoller** [comment]
> Leider sind in der neuen API nicht alle Informationen wie früher (wie z. B. Füllhöhe in cm) abrufbar.

Habe ich auch grad gesehen, allerdings kann die Mobile App es noch anzeigen. Die kommt auch irgendwie an die Daten. ;-) Ich bin ja schon froh, dass Fix Insights hier mal im Gegensatz zu anderen einen Schritt macht, dass wir an die Daten kommen können. Andere Dienstleister tun alles, um das zu verhindern.

**Comment by Rabenauer** [comment]
> bin auch betroffen. Die wohl wichtigste Frage ist für mich: Wie geht es denn hier weiter? Den Dokulink von Foxinsights kann ich nicht verstehen. Wer hat denn diesen ursprünglichen Adapter "erstellt"? Wer versteht den diese für mich unverständlichen Programmieranweisungen? Schade, dass derartige Spontanitäten mir den Spaß an der Sache ioBroker verderben. Aber okay, was solls. Bin halt einfach nur zu doof.
> 
> VG Schlumpel

@Schlumpel mal ganz ruhig ;-). Der Adapter funzt gerade mal einen Tag nicht und der Entwickler wartet sicher nicht darauf daß er da was korrigieren kann. Es ist auch nur der Oilfox Adapter, es geht die Welt nicht unter wenn der mal nicht geht.

**Comment by jogibear9988** [comment]
mein problem hier nun ist, das ich den oilfox selbst nicht mehr nutze, hab auf ne wärmepumpe umgestellt. Daher ist meine motivation da was zu tun leider recht niedrig + ich hab  ja keinen mehr zum testen.

Kp. wann ich dazu komme. Aber falls jm. einen pull req hat, nur her damit.

**Comment by proper0912** [comment]
Hi, also ich würde das gerne übernehmen. Aber ich habe nicht die Erfahrung mit https request. 
Falls mir jemand das erklärt dann würde ich mich daran gehen. Da ich ein OilFox besitzte.

**Comment by inidona** [comment]
ich habe PR-78 erstellt, bei mir kommen jetzt wieder Werte an.

**Comment by inidona** [comment]
#78

**Comment by MiGoller** [comment]
Ich habe auch einen OilFox. Mit Postman habe ich die neue Customer-Api ausprobiert: Das funktioniert, liefert nur deutlich weniger Infos als die bisherige API. Der Bearer-Token des neuen Logins funktioniert in meinen Tests auch nicht mit der alten API (vgl. `summary`), die bisher genutzt wird. Es kommt ein 400er Fehler zurück.

Die Mobile App habe ich über einen HTTPS Proxy geschickt, aber das sieht nach Google Firebase aus... keine direkten API-Calls mehr. Eine schnelle Lösung, die alte Funktionalität wieder herzustellen, sehe ich nicht mehr. Ich grübele noch ein wenig... vielleicht habe ich noch eine Idee.

**Comment by peoples0815** [comment]
> #78

Habe den Commit bei mir auch mal händisch eingepflegt, funktioniert auch bei mir

Danke!

**Comment by inidona** [comment]
@jogibear9988  können wir dann mal wieder ein echtes NPM Release machen ? Oder kann ich den Adapter übernehmen ?

**Comment by Apollon77** [comment]
Hi @inidona, setzte Adapter - bzw den PR auf meine Liste ... sorry hatte ich bisher nicht gesehen. Wenn DU interesse hast den Adapter zu Maintainen freuen wir uns auch drüber! Können wir weiter über PRs machen und wir releasen oder ich kann Dir auch Adapter Zugriff geben.

**Comment by jogibear9988** [comment]
@inidona ich hab den pull gemerged.
von mir aus kannst du den adapter gerne maintainen, wie gesagt ich hab keinen mehr. :-)

**Comment by Apollon77** [comment]
@jogibear9988 ok, dann bringe ich den adapter nachher/morgen auf den Standardstand und das wäre dann basis für die Zukunft. @inidona Können gern hier oder auch im Discord oder Telegram oder Forum direkt kommunizeiren

**Comment by Apollon77** [comment]
So, GitHub hat ein update mit formalitäten bekommen :-) (https://github.com/iobroker-community-adapters/ioBroker.oilfox/commit/1117f748d41d117e301a51187599bb13f8a18f23) und wenn wir eh ne 4.0 machen können wir auch das Passwort verschlüsseln.

@inidona Bitte noch die Info posten was user tun müssen wegen neuer API? Oder ist das Cloud updates und hat eh schon jeder?

Ansonsten gern alle mal GitHub version testen!

Ich warte auf Euer Feedback bevor ich was release

**Comment by bakerman23** [comment]
Eine Neuinstallation ist zwingend erforderlich. Danach funktioniert es super.
Ihr seid die Besten.

**Comment by inidona** [comment]
@Apollon77 der Adapter funktioniert weiter. Allerdings hat sich die Datenstruktur geändert und daher haben die Datenpunkte einen neuen Namen bekommen.

**Comment by MarioSander** [comment]
> So, GitHub hat ein Update mit Formalitäten bekommen :-) ( [1117f74](https://github.com/iobroker-community-adapters/ioBroker.oilfox/commit/1117f748d41d117e301a51187599bb13f8a18f23) ) und wenn wir eh ne 4.0 machen können wir auch das Passwort verschlüsseln.
> 
> Auch die Basis-Tests habe ich gefixt und laufen jetzt auf GitHub-Aktionen.
> 
> @inidona Bitte noch die Info posten was user tun & wegen neuer API? Oder ist das Cloud-Update und hat eh schon jeder?
> 
> Bitte gern alle mal GitHub-Version testen!
> 
> Ich warte auf Euer Feedback, bevor ich veröffentlicht wurde

Github Version funktioniert bestens.
Super vielen Dank

**Comment by Apollon77** [comment]
@inidona Ok, dann packe ich das mit in die Admin upgrade meldung, dann wissen alle user bescheid.

**Comment by Apollon77** [comment]
release der 4.0 geht heite abend raus

**Comment by MiGoller** [comment]
> @jogibear9988 ok, dann bringe ich den adapter nachher/morgen auf den Standardstand und das wäre dann basis für die Zukunft. @inidona Können gern hier oder auch im Discord oder Telegram oder Forum direkt kommunizeiren

Hallo zusammen. Wenn es meine Zeit zulässt, unterstütze ich hier gern. Habe auch noch einen OilFox im Einsatz.

**Comment by Rabenauer** [comment]
Super, ihr seid Spitze 👋. Vielen Dank für das schnelle Update.
Nun müsste mir nur noch mein Oilfox Passwort wieder einfallen was ich nach Neuinstallation brauche.

**Comment by Apollon77** [comment]
EInfach VOR dem Update im Admin - Objekte -Expertenmodus aktivieren -system.adapteroilfox.0 mit Stift-Icon aufrufen, dort in "Native" steht es

**Comment by Rabenauer** [comment]
> EInfach VOR dem Update im Admin - Objekte -Expertenmodus aktivieren -system.adapteroilfox.0 mit Stift-Icon aufrufen, dort in "Native" steht es

Vielen Dank @Apollon77 für den Tipp, der war super ! Eigentlich war es zu spät, aber im ältesten der 5 Proxmox Backups war noch der alte Adapter drin. Also Problem gelöst !
