### ISSUE TITLE
Keine Objekte nach Installation von Oilfox 402

### ISSUE THREAD

**Issue by atuk19** [iobroker-community-adapters/ioBroker.oilfox#79]
Da ich seit 4 Tagen keine aktuellen Werte mehr vom Oilfox erhielt, habe ich voller Hoffnung die Version 4.0.2 installiert.
Die Instanz ist vorhanden, EMail und Passwort sind eingetragen aber es werden keine Objekte erzeugt.
Hat jemand einen heißen Tip?

**Comment by tofrie** [comment]
Ich habe das gleiche Problem…

**Comment by atuk19** [comment]
Die Datenpunkte sind wieder vorhanden. Nachdem der Oilfox sein Paket gesendet hatte  sind unter dem Ordner 0 acht Datenpunkte erschienen, die alle wichtigen Werte anzeigen. Offensichtlich erstellt der IOB die Datenpunkte erst nachdem er ein neues Telegram vom Sender erhalten hat.
