### ISSUE TITLE
can not start version 4.0.2

### ISSUE THREAD

**Issue by Garbracht** [iobroker-community-adapters/ioBroker.oilfox#81]
I nutze den IoBroker um den Füllstand meines Tanks zu visualisieren. Seit dem 24. 3. habe ich keine Messwerte mehr bekommen. Nach längerer Suche habe ich dann festgestellt, daß es eine neue Version gibt, bei der sich die Datenpunkte von der alten Version unterscheiden. 
Ich habe dann die Version 4.0.2 heruntergeladen und versucht die installierte Version zu überschreiben. Das funktionierte zunächst auch, doch nach einigen Minuten wurde die alte Version 3.0.0 als installiert angezeigt. Unter 3.0.0 werden die Daten allerdings nicht richtig eingelesen.
Dann habe ich den installierten Adapter gelöscht und 4.0.2 wieder geladen. Das gleiche Bild wie oben. Eine Instanz oder Objekte werden nicht mehr angezeigt. 
In de APP werden alle Daten korrekt angezeigt.
Was kann ich tun? Hat noch jemand diese Problemen?

**Comment by Apollon77** [comment]
is 4.1.2 working?

**Comment by Garbracht** [comment]
Sorry for the delay, was on Corona for the last days. Yes, 4.1.2 is running for more than a week now. Working well. After installation I had to start the instance manually. But maybe this was caused by my previous trials. Thank you for the great adapter.
