### ISSUE TITLE
Error in GUI - No instance created

### ISSUE THREAD

**Issue by Garbracht** [iobroker-community-adapters/ioBroker.oilfox#83]
I have installed the new version 4.1.1 . 
No instance has been created. I tried to install it manually from the adaptor repository. 
When opening Einstellungen in instances I get an error message. 

Error in GUI: 

Translation for word "Main settings" in "de" was ignored: existing = "Allgemeine Einstellungen", new = Haupteinstellungen instrument.ts:124:32
TypeError: can't convert undefined to object
    value ConfigPanel.js:124
    value ConfigPanel.js:262
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value index.js:148
instrument.ts:124:32
    Z instrument.ts:124
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value index.js:148 

I got the same result with differnt browswers. 

Plesae post a message when you have fixed it.

**Comment by MarioSander** [comment]
hallo
 bei mir jetzt leider auch.
habe auf 4.1.1 umgestellt, jetzt komme ich nicht mehr in die Einstellungen

**Comment by Goeste** [comment]
Der Fehler ist mit Version 4.1.2 gefixt.
