### ISSUE TITLE
No data since 2022-10-11

### ISSUE THREAD

**Issue by Garbracht** [iobroker-community-adapters/ioBroker.oilfox#97]
I did not get any new data since 2022-10-11. 
My IOS App is working. 

Have there been any changes at Oilfox? 

I am using version 4.1.2

regards

System info:
PlatformBetriebssystem:linux
Architektur:x64
CPUs:2
Geschwindigkeit:3400 MHz
Modell:Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
RAM:4 GB
System-Betriebszeit:42 T. 14:20:50
Node.js:v14.20.0
time:1668585160266
timeOffset:--
Adapter-Anzahl:444
NPM:6.14.17
Datenträgergröße:19.5 GB
Freier Festplattenspeicher:12.4 GB
Betriebszeit:42 T. 14:20:48
Aktive Instanzen:19
Pfad:/opt/iobroker/
aktiv:true
_nodeCurrent:14.20.0
_nodeNewest:14.21.1
_nodeNewestNext:16.18.1
_npmCurrent:6.14.17
_npmNewest:6.14.17
_npmNewestNext:8.19.2

**Comment by inventbox1** [comment]
Hi,

same here: GENERIC__INTERNAL_SERVER_ERROR | 500

**Comment by Viper525** [comment]
Same on my side just set up from scretch (newbee) on a bananapi M5.
No instances get listed in OilFox Object folder.

**Comment by derLoosi** [comment]
Same problem here, re-installing the adapter did not solve it.

```
errorCode: GENERIC__INTERNAL_SERVER_ERROR
statusCode: 500
```

App is working fine.
Maybe they changed the API?

**Comment by TobiRabid** [comment]
+1 
Server ERROR 500 
no new data

**Comment by mcm1957** [comment]
Hi, do not have an oilfox hardware - so not sure if I can do anything.

But as a first try, please start the adapter using loglevel debug and post the output here.
Please verify that no sensitive data (i.e.passwords) is logged and masked them if present in log output.

As far as a short check of oilfox website displyed, the username (mailaddress) and password would allow access to the ordering system too. So its for sure no option to ask for an existing account to test. (I would not even accept such sensitive data if someone is willing to share!),

So as a first step, please proivide the debug log if still interesed in the adapter.

Note: I do not have much time to spend, so it could last some time to respond!

**Comment by TobiRabid** [comment]
The problem seems that the adapter is always running....
<html><body>


host.buanet-iobroker1 |   | 2023-08-16 11:00:00.029 | warn | instance system.adapter.oilfox.0 already running with pid 29054
-- | -- | -- | -- | --
host.buanet-iobroker1 |   | 2023-08-16 10:59:00.011 | warn | instance system.adapter.oilfox.0 already running with pid 29054
host.buanet-iobroker1 |   | 2023-08-16 10:12:01.828 | info | instance scheduled system.adapter.oilfox.0 */59 * * * *
host.buanet-iobroker1 |   | 2023-08-16 10:11:58.805 | info | stopInstance system.adapter.oilfox.0 (force=false, process=true)
host.buanet-iobroker1 |   | 2023-08-16 10:11:58.804 | info | "system.adapter.oilfox.0" enabled
host.buanet-iobroker1 |   | 2023-08-16 10:11:54.812 | info | stopInstance system.adapter.oilfox.0 (force=false, process=true)


</body>
</html>

**Comment by mcm1957** [comment]
@TobiRabid 
This looks like a different problem as the original issue states clearly that an http 500 is logged.

**Comment by TobiRabid** [comment]
![Screenshot 2023-08-16 120235](https://github.com/iobroker-community-adapters/ioBroker.oilfox/assets/141586678/628c312c-2589-40fd-a311-199a69738e15)

attached the state from the object page

**Comment by mcm1957** [comment]
Please retry with current release 4.2.0

**Comment by dispo112** [comment]
Oilfox is now on version 4.2.0. No data point is being written, and the objects are empty. I've set the logging to debug mode, hoping to get some useful information out of it.

**Comment by Ilovegym66** [comment]
Hi, here is working fine, with Node 18.17.0, NPM 9.6.0, Debian Bookworm, js-controller 5.0.12.
How is the schedule in the adapter set in your config?
You know, the oilfox transfer the data only one time per day to the server, and the adapter need only a schedule of some hours..
here you can edit the schedule time, in my example is every hour at 55..
![image](https://github.com/iobroker-community-adapters/ioBroker.oilfox/assets/36229898/a0fd9403-708a-43cb-bef3-437ded5cedd7)
so set the adapter to debug and wait if the schedule is running, please.

**Comment by mcm1957** [comment]
@dispo112
> Oilfox is now on version 4.2.0. No datapoint is being written, and the objects are empty. I've set the logging to debug mode, hoping to get some useful information out of it.

Sorry - I'll try to help locating the issue although I do not have oilfox access and/or hardware.

If the log does not provide useful infos, would you accept to install a giuthub version? The only way I see to diagnose you problem would be to add additional debug logs. I would like to spam latest repo with too many releases just for diagnoe purposes if possible.

**Comment by dispo112** [comment]
> @dispo112
> 
> > Oilfox is now on version 4.2.0. No datapoint is being written, and the objects are empty. I've set the logging to debug mode, hoping to get some useful information out of it.
> 
> Sorry - I'll try to help locating the issue although I do not have oilfox access and/or hardware.
> 
> If the log does not provide useful infos, would you accept to install a giuthub version? The only way I see to diagnose you problem would be to add additional debug logs. I would like to spam latest repo with too many releases just for diagnoe purposes if possible.

"Data point deleted, adapter removed. Everything reinstalled. It's running without errors now. I'm not sure why it didn't work last week. Everything is fine now, all data points are present. THANK YOU!

**Comment by mcm1957** [comment]
Thanks for feedback.
Lets wait some time if issue reoccures

**Comment by mcm1957** [comment]
Ok, no more issues reported.
I'll close here.

If new problems occure, please open a new issue
